apiVersion: apps/v1
kind: Deployment
metadata:
  name: supportbot_telegram
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
      matchLabels:
        app: supportbot_telegram
  template:
    metadata:
      labels:
        app: supportbot_telegram
    spec:
      containers:
      - name: supportbot_telegram
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m